//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyClient.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.IMyCompanyPublicService")]
    public interface IMyCompanyPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompanyPublicService/GetPublicInformation", ReplyAction="http://tempuri.org/IMyCompanyPublicService/GetPublicInformationResponse")]
        string GetPublicInformation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyCompanyPublicServiceChannel : CompanyClient.CompanyService.IMyCompanyPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyCompanyPublicServiceClient : System.ServiceModel.ClientBase<CompanyClient.CompanyService.IMyCompanyPublicService>, CompanyClient.CompanyService.IMyCompanyPublicService {
        
        public MyCompanyPublicServiceClient() {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicInformation() {
            return base.Channel.GetPublicInformation();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.IMyCompanyConfidentialService")]
    public interface IMyCompanyConfidentialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompanyConfidentialService/GetCofidentialInformation", ReplyAction="http://tempuri.org/IMyCompanyConfidentialService/GetCofidentialInformationRespons" +
            "e")]
        string GetCofidentialInformation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyCompanyConfidentialServiceChannel : CompanyClient.CompanyService.IMyCompanyConfidentialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyCompanyConfidentialServiceClient : System.ServiceModel.ClientBase<CompanyClient.CompanyService.IMyCompanyConfidentialService>, CompanyClient.CompanyService.IMyCompanyConfidentialService {
        
        public MyCompanyConfidentialServiceClient() {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyConfidentialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyConfidentialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCofidentialInformation() {
            return base.Channel.GetCofidentialInformation();
        }
    }
}
