//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebApplication.HelloWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://marek2222.com/WebServices", ConfigurationName="HelloWebService.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name nazwa from namespace http://marek2222.com/WebServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marek2222.com/WebServices/Powitanie", ReplyAction="*")]
        HelloWebApplication.HelloWebService.PowitanieResponse Powitanie(HelloWebApplication.HelloWebService.PowitanieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PowitanieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Powitanie", Namespace="http://marek2222.com/WebServices", Order=0)]
        public HelloWebApplication.HelloWebService.PowitanieRequestBody Body;
        
        public PowitanieRequest() {
        }
        
        public PowitanieRequest(HelloWebApplication.HelloWebService.PowitanieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marek2222.com/WebServices")]
    public partial class PowitanieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nazwa;
        
        public PowitanieRequestBody() {
        }
        
        public PowitanieRequestBody(string nazwa) {
            this.nazwa = nazwa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PowitanieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PowitanieResponse", Namespace="http://marek2222.com/WebServices", Order=0)]
        public HelloWebApplication.HelloWebService.PowitanieResponseBody Body;
        
        public PowitanieResponse() {
        }
        
        public PowitanieResponse(HelloWebApplication.HelloWebService.PowitanieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marek2222.com/WebServices")]
    public partial class PowitanieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PowitanieResult;
        
        public PowitanieResponseBody() {
        }
        
        public PowitanieResponseBody(string PowitanieResult) {
            this.PowitanieResult = PowitanieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : HelloWebApplication.HelloWebService.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<HelloWebApplication.HelloWebService.HelloWebServiceSoap>, HelloWebApplication.HelloWebService.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebApplication.HelloWebService.PowitanieResponse HelloWebApplication.HelloWebService.HelloWebServiceSoap.Powitanie(HelloWebApplication.HelloWebService.PowitanieRequest request) {
            return base.Channel.Powitanie(request);
        }
        
        public string Powitanie(string nazwa) {
            HelloWebApplication.HelloWebService.PowitanieRequest inValue = new HelloWebApplication.HelloWebService.PowitanieRequest();
            inValue.Body = new HelloWebApplication.HelloWebService.PowitanieRequestBody();
            inValue.Body.nazwa = nazwa;
            HelloWebApplication.HelloWebService.PowitanieResponse retVal = ((HelloWebApplication.HelloWebService.HelloWebServiceSoap)(this)).Powitanie(inValue);
            return retVal.Body.PowitanieResult;
        }
    }
}
